version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: sh -c "npx prisma db push --schema='./prisma/schema.prisma' --accept-data-loss && npx prisma db seed && npm run start:dev"   - 3000:3000
    depends_on:
      - database-db
    networks:
      - database-network

  database-db:
    image: 'bitnami/postgresql'
    container_name: database-db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=techchallenge
    ports:
      - 5434:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - database-network

volumes:
  postgresql_data:
    driver: local

networks:
  database-network:
